# Funding options for geek42.
# Uncomment and fill in any platforms you want to list on the GitHub
# sidebar. Leave commented for no funding links.

# github: [OWNER]
# custom: ["https://example.org/donate"]
# ko_fi: OWNER
# liberapay: OWNER
# open_collective: geek42
# patreon: OWNER
# tidelift: "pypi/geek42"
