"""Verify local distribution files against all supply-chain providers.

Verifies files in dist/ against five independent proof providers:

1. SHA256 checksums       — release checksums from GitHub Release
2. Sigstore signatures    — keyless OIDC signing bundles from GitHub Release
3. GitHub attestations    — build provenance in GitHub's attestation API
4. SLSA L3 provenance     — non-falsifiable provenance from an isolated builder
5. PyPI attestations      — PEP 740 publish attestations from PyPI and TestPyPI

Files must already exist in dist/ (build with 'uv build' or download with
'pip download'). Proof artifacts are cached in proofs/{github,pypi}/.

Requirements:
  - gh                (GitHub CLI, for attestation verify + release download)
  - sigstore          (uv tool run sigstore, for sigstore bundle verification)
  - slsa-verifier     (Go binary, for SLSA L3 provenance verification)
  - pypi-attestations (CLI, for PEP 740 attestation verify + inspect)
  - rich              (Python, for pretty output — already a project dependency)

Usage:
    uv run python scripts/verify_provenance.py [VERSION]
    uv run python scripts/verify_provenance.py 0.4.2a7
    uv run python scripts/verify_provenance.py          # auto-detects from __init__.py
"""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
import tomllib
import urllib.parse
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

console = Console()

REPO_ROOT = Path(__file__).resolve().parent.parent
DIST_EXTENSIONS = (".whl", ".tar.gz")

# Known CI providers and their OIDC issuers
KNOWN_HOSTS = {
    "github.com": "https://token.actions.githubusercontent.com",
}

# -- Trust anchors (derived from pyproject.toml) ---------------------------

_pyproject = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text())
PACKAGE_NAME = _pyproject["project"]["name"]
_repo_url = urllib.parse.urlparse(_pyproject["project"]["urls"]["Repository"])
_repo_host = _repo_url.hostname
if _repo_host not in KNOWN_HOSTS:
    console.print(f"[bold red]Unknown repository host: {_repo_host}[/]")
    console.print(f"[dim]Known hosts: {', '.join(KNOWN_HOSTS)}[/]")
    sys.exit(1)
REPO_SLUG = _repo_url.path.strip("/")
OIDC_ISSUER = KNOWN_HOSTS[_repo_host]

# Release conventions — update these if your project uses different values
RELEASE_WORKFLOW = "release.yml"
TAG_PREFIX = "v"  # tags are formatted as v{version}, e.g. v0.4.2a7

# -- Descriptions for each mechanism ----------------------------------

DESCRIPTIONS = {
    "sha256": (
        "[bold]SHA256 checksums[/] verify basic integrity.\n"
        "The release workflow computes SHA256 hashes of all artifacts and\n"
        "writes them to SHA256SUMS.txt. Anyone can re-hash the downloaded\n"
        "files and compare. This catches corruption or tampering in transit,\n"
        "but does NOT prove who built them."
    ),
    "sigstore": (
        "[bold]Sigstore signatures[/] prove the artifact was signed by the\n"
        "release workflow using keyless (OIDC) signing. The signature is\n"
        "recorded in the Rekor transparency log. Verification checks that\n"
        "the signer's certificate was issued to the expected GitHub Actions\n"
        "workflow identity. No long-lived keys are involved."
    ),
    "gh_attestation": (
        "[bold]GitHub attestations[/] (via actions/attest) store build\n"
        "provenance in GitHub's attestation API. They record WHAT was built,\n"
        "by WHICH workflow, at WHICH commit, and are signed via Sigstore.\n"
        "Verification uses 'gh attestation verify' which checks the\n"
        "signature and the artifact's SHA256 against the stored attestation."
    ),
    "slsa_l3": (
        "[bold]SLSA Level 3 provenance[/] is the strongest guarantee.\n"
        "Unlike GitHub attestations (which run in the same workflow),\n"
        "SLSA L3 uses an ISOLATED reusable workflow from\n"
        "slsa-framework/slsa-github-generator that the caller CANNOT\n"
        "tamper with. The provenance is a signed in-toto statement\n"
        "recording source, builder, and artifact digests. Verified with\n"
        "'slsa-verifier' (a Go binary from the SLSA framework)."
    ),
    "pypi_attestation": (
        "[bold]PyPI attestations (PEP 740)[/] are publish attestations\n"
        "generated by pypa/gh-action-pypi-publish and stored in PyPI's\n"
        "Integrity API. They bind each uploaded file to the Trusted\n"
        "Publisher identity (GitHub repo + workflow) via Sigstore.\n"
        "This proves PyPI received the artifact from the expected\n"
        "publisher, not from a compromised token or rogue upload."
    ),
}


# -- Helpers -----------------------------------------------------------


def get_version() -> str:
    if len(sys.argv) > 1:
        return sys.argv[1].removeprefix("v")
    init = REPO_ROOT / "src" / "geek42" / "__init__.py"
    for line in init.read_text().splitlines():
        if line.startswith("__version__"):
            return line.split('"')[1]
    console.print("[red]Could not detect version. Pass it as an argument.[/]")
    sys.exit(1)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, capture_output=True, text=True, check=False, **kwargs)  # noqa: S603 — args are list literals, no shell


def is_dist_file(name: str) -> bool:
    return any(name.endswith(ext) for ext in DIST_EXTENSIONS)


def header(title: str) -> None:
    console.print()
    console.rule(f"[bold blue]{title}[/]")
    console.print()


def ok(msg: str) -> None:
    console.print(f"  [bold green]OK[/] {msg}")


def fail(msg: str) -> None:
    console.print(f"  [bold red]FAIL[/] {msg}")


def info(msg: str) -> None:
    console.print(f"  [dim]{msg}[/]")


def explain(key: str) -> None:
    console.print(Panel(DESCRIPTIONS[key], border_style="dim"))


# -- Collectors --------------------------------------------------------


def collect_local(version: str) -> dict[str, Path]:
    dist_dir = REPO_ROOT / "dist"
    if not dist_dir.is_dir():
        return {}
    return {
        f.name: f for f in sorted(dist_dir.iterdir()) if is_dist_file(f.name) and version in f.name
    }


def download_github_proofs(version: str) -> Path:
    """Download GitHub Release proof files to proofs/github/.

    Includes sigstore bundles, checksums, SBOM, and SLSA provenance.
    """
    gh_proofs = _ensure_proofs_dir() / "github"
    gh_proofs.mkdir(exist_ok=True)
    tag = f"{TAG_PREFIX}{version}"
    result = run(
        [
            "gh",
            "release",
            "download",
            tag,
            "--repo",
            REPO_SLUG,
            "--dir",
            str(gh_proofs),
            "--skip-existing",
        ]
    )
    if result.returncode != 0:
        console.print(f"  [yellow]GitHub Release {tag} not found or download failed[/]")
        if result.stderr:
            info(result.stderr.strip())
    else:
        info("Proof files saved to proofs/github/")
    return gh_proofs


# -- 1. SHA256 checksums ----------------------------------------------


def verify_checksums(artifacts: dict[str, Path], sums_file: Path | None) -> bool:
    expected: dict[str, str] = {}
    if sums_file and sums_file.exists():
        for line in sums_file.read_text().splitlines():
            if line.strip():
                h, name = line.split(None, 1)
                expected[name.strip()] = h.strip()

    all_ok = True
    for name, path in sorted(artifacts.items()):
        actual = sha256(path)
        if name in expected:
            if actual == expected[name]:
                ok(f"{name}: {actual}")
            else:
                fail(f"{name}: expected {expected[name]}, got {actual}")
                all_ok = False
        else:
            info(f"{name}: {actual}")
    return all_ok


# -- 2. Sigstore signatures -------------------------------------------


def _extract_san_from_bundle(bundle_path: Path) -> str | None:
    try:
        bundle_data = json.loads(bundle_path.read_text(encoding="utf-8"))
        cert_b64 = (
            bundle_data.get("verificationMaterial", {}).get("certificate", {}).get("rawBytes", "")
        )
        if not cert_b64:
            return None
        cert_pem = "-----BEGIN CERTIFICATE-----\n" + cert_b64 + "\n-----END CERTIFICATE-----\n"
        result = run(["openssl", "x509", "-noout", "-ext", "subjectAltName"], input=cert_pem)
        if result.returncode != 0:
            return None
        for line in result.stdout.splitlines():
            stripped = line.strip()
            if stripped.startswith("URI:"):
                return stripped.removeprefix("URI:")
    except (json.JSONDecodeError, KeyError):
        pass
    return None


def verify_sigstore(path: Path, bundle: Path | None, version: str) -> bool:
    if not bundle or not bundle.exists():
        info(f"sigstore: no bundle for {path.name}")
        return True

    san = _extract_san_from_bundle(bundle)
    if not san:
        san = f"https://github.com/{REPO_SLUG}/.github/workflows/{RELEASE_WORKFLOW}@refs/tags/{TAG_PREFIX}{version}"

    result = run(
        [
            "uv",
            "tool",
            "run",
            "sigstore",
            "verify",
            "identity",
            "--cert-identity",
            san,
            "--cert-oidc-issuer",
            OIDC_ISSUER,
            "--bundle",
            str(bundle),
            str(path),
        ]
    )
    artifact_hash = sha256(path)
    if result.returncode != 0:
        fail(f"sigstore verify: {path.name}")
        fail(f"  artifact: {artifact_hash}")
        if result.stderr:
            fail(f"  error: {result.stderr.strip().splitlines()[-1]}")
        return False
    ok(f"sigstore verify: {path.name} ({artifact_hash})")
    info(f"  signed by: {san}")
    info(f"  trust root: {OIDC_ISSUER}")
    return True


# -- 3. GitHub attestations -------------------------------------------


def verify_gh_attestation(path: Path) -> dict | None:
    artifact_hash = sha256(path)
    result = run(
        ["gh", "attestation", "verify", str(path), "--repo", REPO_SLUG, "--format", "json"]
    )
    if result.returncode != 0:
        fail(f"gh attestation verify: {path.name}")
        fail(f"  artifact: {artifact_hash}")
        if result.stderr:
            fail(f"  error: {result.stderr.strip().splitlines()[-1]}")
        return None
    ok(f"gh attestation verify: {path.name} ({artifact_hash})")
    info(f"  trust root: {OIDC_ISSUER} (via GitHub)")
    try:
        records = json.loads(result.stdout)
        if isinstance(records, list) and records:
            # Save attestation JSON to proofs/github/
            gh_proofs = _ensure_proofs_dir() / "github"
            gh_proofs.mkdir(exist_ok=True)
            att_file = gh_proofs / f"{path.name}.gh-attestation.json"
            att_file.write_text(json.dumps(records, indent=2))
            info(f"Saved to {att_file.relative_to(REPO_ROOT)}")
            return records[0]
    except json.JSONDecodeError:
        pass
    return None


def print_gh_attestation_details(attestation: dict) -> None:
    vr = attestation.get("verificationResult", {})
    cert = vr.get("signature", {}).get("certificate", {})
    stmt = vr.get("statement", {})
    predicate = stmt.get("predicate", {})
    build_def = predicate.get("buildDefinition", {})
    run_details = predicate.get("runDetails", {})
    workflow = build_def.get("externalParameters", {}).get("workflow", {})
    resolved = build_def.get("resolvedDependencies", [])
    timestamps = vr.get("verifiedTimestamps", [])

    table = Table(title="GitHub Attestation", show_header=False, padding=(0, 2), expand=True)
    table.add_column("Field", style="bold cyan", min_width=24, max_width=30)
    table.add_column("Value", overflow="fold")

    table.add_row("Predicate type", stmt.get("predicateType", "?"))
    table.add_row("Build type", build_def.get("buildType", "?"))
    table.add_row("Workflow", workflow.get("path", "?"))
    table.add_row("Workflow ref", workflow.get("ref", "?"))
    table.add_row("Source repo", workflow.get("repository", "?"))
    if resolved:
        dep = resolved[0]
        table.add_row("Source URI", dep.get("uri", "?"))
        table.add_row("Source commit", dep.get("digest", {}).get("gitCommit", "?"))
    table.add_row("Builder ID", run_details.get("builder", {}).get("id", "?"))
    table.add_row("Invocation", run_details.get("metadata", {}).get("invocationId", "?"))

    github = build_def.get("internalParameters", {}).get("github", {})
    table.add_row("Event", github.get("event_name", "?"))
    table.add_row("Runner", github.get("runner_environment", "?"))

    table.add_row("", "")
    table.add_row("Issuer", cert.get("certificateIssuer", "?"))
    table.add_row("OIDC issuer", cert.get("issuer", "?"))
    table.add_row("SAN", cert.get("subjectAlternativeName", "?"))
    table.add_row("Trigger", cert.get("githubWorkflowTrigger", "?"))

    if timestamps:
        ts = timestamps[0]
        table.add_row("Log timestamp", ts.get("timestamp", "?"))

    subjects = stmt.get("subject", [])
    if subjects:
        table.add_row("", "")
        for subj in subjects:
            digest = subj.get("digest", {}).get("sha256", "?")
            table.add_row(subj.get("name", "?"), f"sha256:{digest}")

    console.print()
    console.print(table)


# -- 4. SLSA L3 provenance --------------------------------------------


def _find_slsa_verifier() -> str:
    """Find slsa-verifier binary, checking common install locations."""
    import shutil

    path = shutil.which("slsa-verifier")
    if path:
        return path
    go_bin = Path.home() / "go" / "bin" / "slsa-verifier"
    if go_bin.exists():
        return str(go_bin)
    return "slsa-verifier"  # let it fail with a clear error


def verify_slsa_provenance(artifact: Path, provenance: Path, version: str) -> bool:
    tag = f"{TAG_PREFIX}{version}"
    verifier = _find_slsa_verifier()
    result = run(
        [
            verifier,
            "verify-artifact",
            "--provenance-path",
            str(provenance),
            "--source-uri",
            f"github.com/{REPO_SLUG}",
            "--source-tag",
            tag,
            "--print-provenance",
            str(artifact),
        ]
    )
    artifact_hash = sha256(artifact)
    if result.returncode != 0:
        fail(f"slsa-verifier: {artifact.name}")
        fail(f"  artifact: {artifact_hash}")
        if result.stderr:
            fail(f"  error: {result.stderr.strip().splitlines()[-1]}")
        return False
    ok(f"slsa-verifier: {artifact.name} ({artifact_hash})")
    info("  signed by: slsa-framework/slsa-github-generator@v2.1.0")
    info(f"  trust root: {OIDC_ISSUER}")

    for line in result.stdout.splitlines():
        try:
            print_slsa_provenance(json.loads(line))
            break
        except json.JSONDecodeError:
            continue
    return True


def print_slsa_provenance(data: dict) -> None:
    pred = data.get("predicate", {})
    cs = pred.get("invocation", {}).get("configSource", {})
    env = pred.get("invocation", {}).get("environment", {})
    meta = pred.get("metadata", {})

    table = Table(title="SLSA L3 Provenance", show_header=False, padding=(0, 2), expand=True)
    table.add_column("Field", style="bold cyan", min_width=24, max_width=30)
    table.add_column("Value", overflow="fold")

    table.add_row("Statement type", data.get("_type", "?"))
    table.add_row("Predicate type", data.get("predicateType", "?"))
    table.add_row("Builder ID", pred.get("builder", {}).get("id", "?"))
    table.add_row("Build type", pred.get("buildType", "?"))
    table.add_row("", "")
    table.add_row("Source URI", cs.get("uri", "?"))
    table.add_row("Source commit", cs.get("digest", {}).get("sha1", "?"))
    table.add_row("Entry point", cs.get("entryPoint", "?"))
    table.add_row("", "")
    table.add_row("Actor", env.get("github_actor", "?"))
    table.add_row("Event", env.get("github_event_name", "?"))
    table.add_row("Ref", env.get("github_ref", "?"))
    table.add_row("Run ID", env.get("github_run_id", "?"))
    table.add_row("Commit SHA", env.get("github_sha1", "?"))
    table.add_row("Invocation ID", meta.get("buildInvocationID", "?"))
    table.add_row("Reproducible", str(meta.get("reproducible", "?")))

    materials = pred.get("materials", [])
    if materials:
        table.add_row("", "")
        for m in materials:
            table.add_row(
                "Material", f"{m.get('uri', '?')}  sha1:{m.get('digest', {}).get('sha1', '?')}"
            )

    subjects = data.get("subject", [])
    if subjects:
        table.add_row("", "")
        for subj in subjects:
            digest = subj.get("digest", {}).get("sha256", "?")
            table.add_row(subj.get("name", "?"), f"sha256:{digest}")

    console.print()
    console.print(table)


# -- 5. PyPI attestations (PEP 740) ------------------------------------

PYPI_INDEX_DIRS = ["pypi", "testpypi"]


def _ensure_proofs_dir() -> Path:
    proofs = REPO_ROOT / "proofs"
    proofs.mkdir(exist_ok=True)
    return proofs


def extract_attestation_file(
    path: Path,
    provenance: dict,
    index_name: str,
) -> Path | None:
    """Extract individual PEP 740 attestation from provenance wrapper.

    The PyPI Integrity API returns a provenance wrapper with
    attestation_bundles[].attestations[], but the pypi-attestations CLI
    expects individual Attestation objects as .publish.attestation files.
    """
    bundles = provenance.get("attestation_bundles", [])
    if not bundles:
        return None
    attestations = bundles[0].get("attestations", [])
    if not attestations:
        return None

    # Save to proofs/{index}/ directory
    index_dir = "testpypi" if index_name == "TestPyPI" else "pypi"
    proofs_dir = _ensure_proofs_dir() / index_dir
    proofs_dir.mkdir(exist_ok=True)
    att_file = proofs_dir / f"{path.name}.publish.attestation"
    att_file.write_text(json.dumps(attestations[0]))

    return att_file


def inspect_attestation(att_file: Path) -> None:
    """Run pypi-attestations inspect to display attestation details."""
    result = run(["uv", "run", "pypi-attestations", "inspect", str(att_file)])
    # inspect writes to stderr (uses rich console internally)
    output = result.stderr or result.stdout
    if result.returncode == 0 and output:
        for line in output.strip().splitlines():
            info(line)


def verify_pypi_attestation(
    path: Path,
    provenance: dict,
    index_name: str,
    version: str,
) -> bool:
    """Verify PyPI PEP 740 attestation using pypi-attestations CLI.

    Uses 'pypi-attestations inspect' for details and
    'pypi-attestations verify attestation' for cryptographic verification.
    """
    bundles = provenance.get("attestation_bundles", [])
    if not bundles:
        fail(f"No attestation bundles in {index_name} provenance")
        return False

    # Extract individual attestation file for CLI
    att_file = extract_attestation_file(path, provenance, index_name)
    if not att_file:
        fail(f"Could not extract attestation from {index_name} provenance")
        return False
    info(f"Extracted attestation to {att_file.name}")

    # Inspect attestation details (unverified display)
    inspect_attestation(att_file)

    # Use local trust anchors for identity — never relax to provenance publisher data
    publisher_data = bundles[0].get("publisher", {})
    identity = (
        f"https://github.com/{REPO_SLUG}"
        f"/.github/workflows/{RELEASE_WORKFLOW}@refs/tags/{TAG_PREFIX}{version}"
    )

    # Warn if publisher data doesn't match trust anchors
    pub_repo = publisher_data.get("repository", "")
    pub_wf = publisher_data.get("workflow", "")
    if pub_repo and pub_repo != REPO_SLUG:
        fail(f"Publisher repo mismatch: {pub_repo} != {REPO_SLUG}")
    if pub_wf and pub_wf != RELEASE_WORKFLOW:
        fail(f"Publisher workflow mismatch: {pub_wf} != {RELEASE_WORKFLOW}")

    # Verify with pypi-attestations CLI
    # CLI expects {artifact}.publish.attestation next to the artifact,
    # so copy both into a temporary directory for verification
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        tmp_artifact = tmp / path.name
        shutil.copy2(path, tmp_artifact)
        shutil.copy2(att_file, tmp / f"{path.name}.publish.attestation")
        result = run(
            [
                "uv",
                "run",
                "pypi-attestations",
                "verify",
                "attestation",
                "--identity",
                identity,
                str(tmp_artifact),
            ]
        )

    artifact_hash = sha256(path)
    if result.returncode != 0:
        fail(f"{index_name}: {path.name}")
        fail(f"  artifact: {artifact_hash}")
        if result.stderr:
            fail(f"  error: {result.stderr.strip()}")
        return False

    ok(f"{index_name}: {path.name} ({artifact_hash})")
    info("  verified by: pypi-attestations verify attestation")
    info(f"  signed by: {pub_repo}/{pub_wf}")
    info(f"  environment: {publisher_data.get('environment', '?')}")
    info(f"  trust root: {OIDC_ISSUER}")

    # Display publisher details table
    table = Table(
        title=f"{index_name} PEP 740 Attestation (verified)",
        show_header=False,
        padding=(0, 2),
        expand=True,
    )
    table.add_column("Field", style="bold cyan", min_width=24, max_width=30)
    table.add_column("Value", overflow="fold")
    table.add_row("Publisher kind", publisher_data.get("kind", "?"))
    table.add_row("Repository", publisher_data.get("repository", "?"))
    table.add_row("Workflow", publisher_data.get("workflow", "?"))
    table.add_row("Environment", publisher_data.get("environment", "?"))
    table.add_row("Predicate type", "https://docs.pypi.org/attestations/publish/v1")
    table.add_row("Artifact", path.name)
    table.add_row("SHA256", artifact_hash)
    console.print()
    console.print(table)

    return True


# -- Main --------------------------------------------------------------


def main() -> int:
    version = get_version()
    console.print(Panel(f"Verifying supply-chain security for [bold]{PACKAGE_NAME} {version}[/]"))

    failures = 0

    # -- Locate artifacts in dist/ -------------------------------------
    header("Distribution files")
    artifacts = collect_local(version)
    if not artifacts:
        console.print(
            Panel(
                f"[bold red]No files matching version {version} found in dist/[/]\n"
                "Build with 'uv build' or download with 'pip download' first.",
            )
        )
        return 1
    console.print(f"  Verifying {len(artifacts)} file(s) from dist/:")
    for name, path in artifacts.items():
        info(f"{name}: {sha256(path)}")

    # -- Download proof files from GitHub Release ----------------------
    header("Downloading proof files")
    gh_proofs = download_github_proofs(version)

    # -- 1. SHA256 checksums -------------------------------------------
    header("1. SHA256 checksums")
    explain("sha256")
    gh_sums = gh_proofs / f"geek42-{version}-SHA256SUMS.txt"
    if not gh_sums.exists():
        gh_sums = gh_proofs / "SHA256SUMS.txt"
    if gh_sums.exists():
        if not verify_checksums(artifacts, gh_sums):
            failures += 1
    else:
        info("No SHA256SUMS.txt found in GitHub Release")

    # -- 2. Sigstore signatures ----------------------------------------
    header("2. Sigstore signatures")
    explain("sigstore")
    for name, path in artifacts.items():
        bundle = gh_proofs / f"{name}.sigstore.json"
        if not bundle.exists():
            bundle = gh_proofs / f"{name}.sigstore"
        if not verify_sigstore(path, bundle, version):
            failures += 1

    # -- 3. GitHub attestations ----------------------------------------
    header("3. GitHub attestations")
    explain("gh_attestation")
    attestation_shown = False
    for _name, path in artifacts.items():
        att = verify_gh_attestation(path)
        if att is None:
            failures += 1
        if att and not attestation_shown:
            print_gh_attestation_details(att)
            attestation_shown = True

    # -- 4. SLSA L3 provenance -----------------------------------------
    header("4. SLSA L3 provenance")
    explain("slsa_l3")
    provenance = gh_proofs / f"geek42-v{version}-provenance.intoto.jsonl"
    if not provenance.exists():
        provenance = gh_proofs / "geek42-provenance.intoto.jsonl"
    if provenance.exists():
        for _name, path in artifacts.items():
            if not verify_slsa_provenance(path, provenance, version):
                failures += 1
            break  # show details once
    else:
        info("No SLSA provenance file found in GitHub Release")

    # -- 5. PyPI / TestPyPI attestations (PEP 740) ---------------------
    header("5. PyPI / TestPyPI attestations (PEP 740)")
    explain("pypi_attestation")
    for idx, index_dir in enumerate(PYPI_INDEX_DIRS, 1):
        index_name = "TestPyPI" if index_dir == "testpypi" else "PyPI"
        header(f"5.{idx} {index_name}")

        if index_dir == "testpypi":
            console.print(
                Panel(
                    "[bold yellow]WARNING: TestPyPI is NOT a production index.[/]\n"
                    "Artifacts here are for testing only. Do not use TestPyPI\n"
                    "packages in production environments.",
                    border_style="yellow",
                )
            )

        proofs_dir = REPO_ROOT / "proofs" / index_dir
        if not proofs_dir.is_dir():
            info(f"{index_name}: no proofs directory (run download_release.py first)")
            continue

        for name, path in artifacts.items():
            prov_file = proofs_dir / f"{name}.provenance.json"
            if not prov_file.exists():
                info(f"{index_name}: no attestation for {name}")
                continue
            prov = json.loads(prov_file.read_text())
            if not verify_pypi_attestation(path, prov, index_name, version):
                failures += 1

    # -- Summary -------------------------------------------------------
    console.print()
    if failures:
        console.print(Panel("[bold red]Verification completed with failures[/]"))
        return 1
    console.print(Panel("[bold green]All verifications passed[/]"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
